[package]
name = "rust_data_loader"
version = "0.1.0"
edition = "2021"

[dependencies]
ureq = { version = "2.9", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"